# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'Sen'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu: 
  - name: Featured Projects
    submenu:
      - name: Genomics
        link: /projects/Genomics
      - name: Transcriptomes
        link: /projects/transcriptomes
  - name: Posts
    link: /
  - name: Tags
    link: /tags
  - name: About
    link: /about
  - name: Follow me
    submenu:
      - name: GitHub
        icon: github
        link: 
      - name: LinkedIn
        icon: linkedin-square
        link: 
      - name: Twitter
        icon: twitter
        link: 
    
